export enum IconTypesEnum {
  Home = 'home',
  Explore = 'explore',
  Bookmarks = 'bookmarks',
  Lists = 'lists',
  Messages = 'messages',
  Notifications = 'notifications',
  Profile = 'profile',
  More = 'more',
  dotsMenu = 'dotsMenu',
  TimelineOptions = 'timelineOptions',
  Emoji = 'emoji',
  Gif = 'gif',
  UploadImg = 'uploadImg',
  Survey = 'survey',
}
