import Head from 'next/head';
import dynamic from 'next/dynamic';

const Sidebar = dynamic(() => import('@/components/Sidebar').then((mod) => mod.Sidebar));

type Props = {
  children: React.ReactNode;
};

const Shell = ({ children }: Props) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex bg-black min-h-screen mx-auto my-0 max-w-screen-xl ">
        <Sidebar />
        {children}
        {/*<AddTweet posts={posts} />*/}
      </main>
    </div>
  );
};

export { Shell };
