import { GetServerSidePropsContext, NextPage } from 'next';
import { getSession } from 'next-auth/react';
import Head from 'next/head';
import { Sidebar } from '@/components/Sidebar';
import { Feed } from '@/components/Feed';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex bg-black min-h-screen mx-auto my-0 max-w-screen-xl ">
        <Sidebar />
        <Feed />
        {/*<Modal/>*/}
      </main>
    </div>
  );
};

export async function getServerSideProps(context: GetServerSidePropsContext) {
  const { req } = context;
  const session = await getSession({ req });

  if (!session?.user) {
    return { redirect: { permanent: false, destination: '/login' } };
  }

  return {
    props: {},
  };
}

export default Home;
