import { GetServerSidePropsContext, InferGetServerSidePropsType } from 'next';
import { getSession } from 'next-auth/react';
import Head from 'next/head';
import { Sidebar } from '@/components/Sidebar';
import { Feed } from '@/components/Feed';
import { collectionGroup, getDocs, limit, orderBy, query } from '@firebase/firestore';
import { firestore } from '../firebase';
import { postToJSON } from '../lib/postToJSON';

const Home = (props: InferGetServerSidePropsType<typeof getServerSideProps>) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex bg-black min-h-screen mx-auto my-0 max-w-screen-xl ">
        <Sidebar profileDetails={props.profile} />
        <Feed posts={props.posts} />
        {/*<Modal/>*/}
      </main>
    </div>
  );
};

export async function getServerSideProps(context: GetServerSidePropsContext) {
  const { req } = context;
  const session = await getSession({ req });

  const collectionRef = collectionGroup(firestore, 'posts');
  const postsQuery = query(collectionRef, orderBy('createdAt', 'desc'), limit(8));
  const postsDocs = await getDocs(postsQuery);
  const posts = postsDocs.docs.map(postToJSON);

  if (!session?.user) {
    return { redirect: { permanent: false, destination: '/login' } };
  } else {
    return {
      props: {
        profile: {
          username: session.user.name,
          tag: session.user.tag,
          id: session.user.id,
        },
        posts,
      },
    };
  }
}

export default Home;
